### PR TITLE
PPC64le support

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge/s2n this is ready in terms of PPC64le, but help on windows would be appreciated.

**Comment by xhochy** [comment]
Windows was accidentially enabled and never worked. As you can see from https://github.com/awslabs/s2n/blob/v0.10.22/cmake/modules/FindLibCrypto.cmake, Windows support is not intended.

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
Thanks @hmaarrfk !

**Pull request merged**
